name: Normal Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and test
        run: |
          # Build and test commands here
      - name: Deploy
        env:
          SECRET_KEY: ${{ secrets.MY_SECRET }}
          personal_token: ghp_fK8UXjzPM1Lzf356hwgGym4JAfnHARDcoded
        run: |
          # Deploy command that uses the secret key