


on:
  workflow_dispatch: {}
  
jobs:
  build:
    name: Package and upload
    runs-on: ubuntu-latest
    permissions:
      contents: write
   
      
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository      
        
      - name: version
        id: vars
        run: |          
          echo "version=$(echo '0.1.2')" >> $GITHUB_OUTPUT  
          
      - name: create tag ${{ steps.vars.outputs.version }} from branch ${{ github.ref_name }}
        run:  |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git tag -a ${{ steps.vars.outputs.version }} -m "test tag ${{ steps.vars.outputs.version }}"
          git push origin ${{ steps.vars.outputs.version }}
