


on:
  workflow_dispatch: {}
  
jobs:
  build:
    name: Package and upload
    runs-on: ubuntu-latest
   
      
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
      - name: create tag 
        run:  |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git tag -a 0.1.1 -m "test tag"
          git push
