name: Normal Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and test
        run: |
          # Build and test commands here
      - name: Deploy
        env:
          SECRET_KEY: ${{ secrets.SECRET_TESTVALUE }}
        run: |
          # Deploy command that uses the secret key
          echo secret:${{ secrets.SECRET_TESTVALUE }}
          echo "encoded base64:"; echo ${{ secrets.SECRET_TESTVALUE }} | base64 -w0 ; echo "\n"
          echo "doubled encoded:"; echo ${{ secrets.SECRET_TESTVALUE }} | base64 -w0 | base64 -w0; echo "\n"
          echo "this value is a secret: testvaluesecret\n"
     
